### ISSUE TITLE
Previewing empty menus doesn't work (depends on #67)

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#7] opened 2015-01-02 20:03 UTC
Create a new menu, add it to a location, add items to it, and it doesn't preview correctly.

**Comment by valendesigns** [comment] 2015-05-22 22:29
This issue isn't exclusive to new menus. Assign an empty menu to a location, add items to it, and it also doesn't preview correctly.

**Comment by designsimply** [comment] 2015-05-30 03:55
This problem showed up in a user test. Here's the related video snippet for reference: [1m38s](https://cloudup.com/cIx2IDNmfzX)

<sup>Pulled from the test at https://make.wordpress.org/design/2015/05/27/customizer-menus-user-testing/#comment-24592 using WP 4.3-alpha-32600 and the Menu Customizer 0.4 (6a6fca3).</sup>

**Comment by valendesigns** [comment] 2015-05-30 04:03
Thank you for the video! It's likely they created the menu and added items to it at the same time as trying to live preview it, which is expected at this point. I can't reproduce the issue unless the menu is empty to begin with or created in the same session. If they had a different experience I would like to know what was done before pressing record. That's the only part I can't account for and have to speculating on.

**Comment by designsimply** [comment] 2015-05-31 02:10
Here's the full video in case you want to have a look: https://make.wordpress.org/design/2015/05/27/customizer-menus-user-testing/#comment-24592

**Comment by celloexpressions** [comment] 2015-05-31 20:09
This is still an issue even with partial refresh enabled. Consider it a blocker at this point.

**Comment by westonruter** [comment] 2015-06-01 23:42
This would also be resolved as part of #67.

**Comment by westonruter** [comment] 2015-06-15 04:28
This was resolved in #73.

**Closed by westonruter** 2015-06-15 04:28 UTC
Labels: bug
